// Shared constants for MEN extra groups
const MEN_EXTRA_GROUPS = ["MEN3", "MEN4", "MEN5", "MEN6"];

const MEN_EXTRA_GROUP_PLACEHOLDERS = {
  MEN3: ["Gender3", "Name3", "CCCD3", "Date3", "Noi_Cap3", "Ngay_Cap3"],
  MEN4: ["Gender4", "Name4", "CCCD4", "Date4", "Noi_Cap4", "Ngay_Cap4"],
  MEN5: ["Gender5", "Name5", "CCCD5", "Date5", "Noi_Cap5", "Ngay_Cap5"],
  MEN6: ["Gender6", "Name6", "CCCD6", "Date6", "Noi_Cap6", "Ngay_Cap6"],
};

const landTypeMap = {
  LUC: "Đất chuyên trồng lúa nước",
  LUK: "Đất trồng lúa nước còn lại",
  LUN: "Đất lúa nương",
  BHK: "Đất bằng trồng cây hằng năm khác",
  NHK: "Đất nương rẫy trồng cây hằng năm khác",
  CLN: "Đất trồng cây lâu năm",
  RSX: "Đất rừng sản xuất",
  RPH: "Đất rừng phòng hộ",
  RDD: "Đất rừng đặc dụng",
  NTS: "Đất nuôi trồng thủy sản",
  LMU: "Đất làm muối",
  NKH: "Đất nông nghiệp khác",
  ONT: "Đất ở tại nông thôn",
  ODT: "Đất ở tại đô thị",
  TSC: "Đất xây dựng trụ sở cơ quan",
  DTS: "Đất xây dựng trụ sở sự nghiệp",
  DVH: "Đất xây dựng cơ sở văn hóa",
  DYT: "Đất xây dựng cơ sở y tế",
  DGD: "Đất xây dựng cơ sở giáo dục và đào tạo",
  DTT: "Đất xây dựng cơ sở thể dục thể thao",
  DKH: "Đất xây dựng cơ sở khoa học và công nghệ",
  DXH: "Đất xây dựng cơ sở dịch vụ xã hội",
  DNG: "Đất xây dựng cơ sở ngoại giao",
  DSK: "Đất xây dựng công trình sự nghiệp khác",
  CQP: "Đất quốc phòng",
  CAN: "Đất an ninh",
  SKK: "Đất khu công nghiệp",
  SKT: "Đất khu chế xuất",
  SKN: "Đất cụm công nghiệp",
  SKC: "Đất cơ sở sản xuất phi nông nghiệp",
  TMD: "Đất thương mại, dịch vụ",
  SKS: "Đất sử dụng cho hoạt động khoáng sản",
  SKX: "Đất sản xuất vật liệu xây dựng, làm đồ gốm",
  DGT: "Đất giao thông",
  DTL: "Đất thủy lợi",
  DNL: "Đất công trình năng lượng",
  DBV: "Đất công trình bưu chính, viễn thông",
  DSH: "Đất công trình công cộng",
  DKV: "Đất khu vui chơi, giải trí công cộng",
  DCH: "Đất chợ",
  DDT: "Đất có di tịch lịch sử – văn hoá",
  DDL: "Đất danh lam thắng cảnh",
  DRA: "Đất bãi thải, xử lý chất thải",
  DCK: "Đất công trình công cộng khác",
  TON: "Đất tôn giáo",
  TIN: "Đất tín ngưỡng",
  NTD: "Đất nghĩa trang, nghĩa địa, nhà tang lễ, nhà hỏa táng",
  SON: "Đất sông ngòi, kênh, rạch, suối",
  MNC: "Đất mặt nước chuyên dùng",
  PNK: "Đất phi nông nghiệp khác",
  BCS: "Đất bằng chưa sử dụng",
  DCS: "Đất đồi núi chưa sử dụng",
  NCS: "Đất chưa sử dụng khác",
};

const phMapping = {
  Gender1: {
    label: "Giới tính",
    type: "select",
    options: ["Ông", "Bà"],
    defaultValue: "Ông",
    group: "BCN",
    subgroup: "MEN1",
  },
  Gender2: {
    label: "Giới tính",
    type: "select",
    options: ["Ông", "Bà"],
    defaultValue: "Bà",
    group: "BCN",
    subgroup: "MEN2",
  },
  Gender3: {
    label: "Giới tính",
    type: "select",
    options: ["Ông", "Bà"],
    group: "BCN",
    subgroup: "MEN3",
  },
  Gender4: {
    label: "Giới tính",
    type: "select",
    options: ["Ông", "Bà"],
    group: "BCN",
    subgroup: "MEN4",
  },
  Gender5: {
    label: "Giới tính",
    type: "select",
    options: ["Ông", "Bà"],
     group: "BCN",
    subgroup: "MEN5",
  },
  Gender6: {
    label: "Giới tính",
    type: "select",
    options: ["Ông", "Bà"],
    group: "BCN",
    subgroup: "MEN6",
  },
  Gender7: {
    label: "Giới tính",
    type: "select",
    options: ["Ông", "Bà"],
    defaultValue: "Ông",
    group: "NCN",
    subgroup: "MEN7",
  },
  Name1: { label: "Họ và tên", type: "text", group: "BCN", subgroup: "MEN1" },
  MST1: { label: "Mã số thuế", type: "number", group: "BCN", subgroup: "MEN1" },
  MST7: { label: "Mã số thuế", type: "number", group: "NCN", subgroup: "MEN7" },
  SDT_MEN1: { label: "Số điện thoại", type: "number", group: "BCN", subgroup: "MEN1" },
  EMAIL_MEN1: { label: "Hộp thư điện tử", type: "text", group: "BCN", subgroup: "MEN1" },
  SDT_MEN7: { label: "Số điện thoại", type: "number", group: "NCN", subgroup: "MEN7" },
  EMAIL_MEN7: { label: "Hộp thư điện tử", type: "text", group: "NCN", subgroup: "MEN7" },
  Name2: { label: "Họ và tên", type: "text", group: "BCN", subgroup: "MEN2" },
  Name3: { label: "Họ và tên", type: "text", group: "BCN", subgroup: "MEN3" },
  Name4: { label: "Họ và tên", type: "text", group: "BCN", subgroup: "MEN4" },
  Name5: { label: "Họ và tên", type: "text", group: "BCN", subgroup: "MEN5" },
  Name6: { label: "Họ và tên", type: "text", group: "BCN", subgroup: "MEN6" },
  Name7: { label: "Họ và tên", type: "text", group: "NCN", subgroup: "MEN7" },
  CCCD1: { label: "CCCD", type: "number", group: "BCN", subgroup: "MEN1" },
  CCCD2: { label: "CCCD", type: "number", group: "BCN", subgroup: "MEN2" },
  CCCD3: { label: "CCCD", type: "number", group: "BCN", subgroup: "MEN3" },
  CCCD4: { label: "CCCD", type: "number", group: "BCN", subgroup: "MEN4" },
  CCCD5: { label: "CCCD", type: "number", group: "BCN", subgroup: "MEN5" },
  CCCD6: { label: "CCCD", type: "number", group: "BCN", subgroup: "MEN6" },
  CCCD7: { label: "CCCD", type: "number", group: "NCN", subgroup: "MEN7" },
  Date1: { label: "Ngày sinh", type: "date", group: "BCN", subgroup: "MEN1" },
  Date2: { label: "Ngày sinh", type: "date", group: "BCN", subgroup: "MEN2" },
  Date3: { label: "Ngày sinh", type: "date", group: "BCN", subgroup: "MEN3" },
  Date4: { label: "Ngày sinh", type: "date", group: "BCN", subgroup: "MEN4" },
  Date5: { label: "Ngày sinh", type: "date", group: "BCN", subgroup: "MEN5" },
  Date6: { label: "Ngày sinh", type: "date", group: "BCN", subgroup: "MEN6" },
  Date7: { label: "Ngày sinh", type: "date", group: "NCN", subgroup: "MEN7" },
  Noi_Cap1: {
    label: "Nơi cấp",
    type: "select",
    options: ["Cục Cảnh sát QLHC về TTXH cấp", "Công an T. Đắk Lắk cấp"],
    group: "BCN",
    subgroup: "MEN1",
  },
  Noi_Cap2: {
    label: "Nơi cấp",
    type: "select",
    options: ["Cục Cảnh sát QLHC về TTXH cấp", "Công an T. Đắk Lắk cấp"],
    group: "BCN",
    subgroup: "MEN2",
  },
  Noi_Cap3: {
    label: "Nơi cấp",
    type: "select",
    options: ["Cục Cảnh sát QLHC về TTXH cấp", "Công an T. Đắk Lắk cấp"],
    group: "BCN",
    subgroup: "MEN3",
  },
  Noi_Cap4: {
    label: "Nơi cấp",
    type: "select",
    options: ["Cục Cảnh sát QLHC về TTXH cấp", "Công an T. Đắk Lắk cấp"],
    group: "BCN",
    subgroup: "MEN4",
  },
  Noi_Cap5: {
    label: "Nơi cấp",
    type: "select",
    options: ["Cục Cảnh sát QLHC về TTXH cấp", "Công an T. Đắk Lắk cấp"],
    group: "BCN",
    subgroup: "MEN5",
  },
  Noi_Cap6: {
    label: "Nơi cấp",
    type: "select",
    options: ["Cục Cảnh sát QLHC về TTXH cấp", "Công an T. Đắk Lắk cấp"],
    group: "BCN",
    subgroup: "MEN6",
  },
  Noi_Cap7: {
    label: "Nơi cấp",
    type: "select",
    options: ["Cục Cảnh sát QLHC về TTXH cấp", "Công an T. Đắk Lắk cấp"],
    group: "NCN",
    subgroup: "MEN7",
  },
  Ngay_Cap1: {
    label: "Ngày cấp",
    type: "date",
    group: "BCN",
    subgroup: "MEN1",
  },
  Ngay_Cap2: {
    label: "Ngày cấp",
    type: "date",
    group: "BCN",
    subgroup: "MEN2",
  },
  Ngay_Cap3: {
    label: "Ngày cấp",
    type: "date",
    group: "BCN",
    subgroup: "MEN3",
  },
  Ngay_Cap4: {
    label: "Ngày cấp",
    type: "date",
    group: "BCN",
    subgroup: "MEN4",
  },
  Ngay_Cap5: {
    label: "Ngày cấp",
    type: "date",
    group: "BCN",
    subgroup: "MEN5",
  },
  Ngay_Cap6: {
    label: "Ngày cấp",
    type: "date",
    group: "BCN",
    subgroup: "MEN6",
  },
  Ngay_Cap7: {
    label: "Ngày cấp",
    type: "date",
    group: "NCN",
    subgroup: "MEN7",
  },
  Address1: {
    label: "Địa chỉ",
    type: "address",
    group: "BCN",
    subgroup: "MEN1",
  },
  Address2: {
    label: "Địa chỉ",
    type: "address",
    group: "NCN",
    subgroup: "MEN7",
  },
  QSH: {
    label: "Quyền sử dụng đất",
    type: "text",
    group: "LAND",
    subgroup: "INFO",
  },
  So_so: { label: "Số sổ", type: "text", group: "LAND", subgroup: "INFO" },
  Ngay_CapD: {
    label: "Ngày cấp",
    type: "date",
    group: "LAND",
    subgroup: "INFO",
  },
  Thua_dat_so: {
    label: "Thửa đất số",
    type: "text",
    group: "LAND",
    subgroup: "INFO",
  },
  Ban_do_so: {
    label: "Bản đồ số",
    type: "text",
    group: "LAND",
    subgroup: "INFO",
  },
  S: { label: "Diện tích(m2)", type: "text", group: "LAND", subgroup: "INFO" },
  Loai_Dat: {
    label: "Loại đất",
    type: "text",
    group: "LAND",
    subgroup: "INFO",
  },
  VTTD:{
    label: "Vị trí thửa đất",
    type: "text",
    group: "LAND",
    subgroup: "INFO",
  },
  THSD: {
    label: "Thời hạn sử dụng",
    type: "text",
    group: "LAND",
    subgroup: "INFO",
  },
  HTSD: {
    label: "Hình thức sử dụng",
    type: "select",
    options: ["Sử dụng chung", "Sử dụng riêng"],
    group: "LAND",
    subgroup: "INFO",
  },
  Address3: {
    label: "Địa chỉ thửa đất",
    type: "address",
    group: "LAND",
    subgroup: "INFO",
  },
  TTGLVD: {
    label: "Thông tin tài sản gắn liền với đất",
    type: "text",
    group: "LAND",
    subgroup: "INFO",
  },
  Note: { label: "Ghi chú", type: "text", group: "LAND", subgroup: "INFO" },
  Money: {
    label: "Giá chuyển nhượng",
    type: "text",
    group: "LAND",
    subgroup: "INFO",
  },
  MoneyText: {
    label: "Giá chuyển nhượng (chữ)",
    type: "text",
    group: "LAND",
    subgroup: "INFO",
  },
  Reponsibility: {
    label: "Trách nhiệm",
    type: "select",
    options: ["A", "B"],
    group: "LAND",
    subgroup: "INFO",
  },
  // BD Group - Thông tin đăng ký biến động đất đai
  BD_Gender: {
    label: "Giới tính",
    type: "select",
    options: ["Ông", "Bà"],
    group: "BD",
    subgroup: "INFO",
  },
  BD_Name: {
    label: "Họ và tên",
    type: "text",
    group: "BD",
    subgroup: "INFO",
  },
  BD_CCCD: {
    label: "Số CCCD",
    type: "number",
    group: "BD",
    subgroup: "INFO",
  },
  BD_Date: {
    label: "Ngày sinh",
    type: "date",
    group: "BD",
    subgroup: "INFO",
  },
  BD_Noi_Cap: {
    label: "Nơi cấp",
    type: "text",
    group: "BD",
    subgroup: "INFO",
  },
  BD_Ngay_Cap: {
    label: "Ngày cấp",
    type: "date",
    group: "BD",
    subgroup: "INFO",
  },
  BD_SDT: {
    label: "Số điện thoại",
    type: "number",
    group: "BD",
    subgroup: "INFO",
  },
  BD_Email: {
    label: "Hộp thư điện tử",
    type: "text",
    group: "BD",
    subgroup: "INFO",
  },
  // UQ Group - Thông tin ủy quyền
  // Bên A - Người ủy quyền (tự động từ MEN1/MEN7)
  UQA_Gender: {
    label: "Giới tính",
    type: "select",
    options: ["Ông", "Bà"],
    group: "UQ",
    subgroup: "BENA",
  },
  UQA_Name: {
    label: "Họ và tên",
    type: "text",
    group: "UQ",
    subgroup: "BENA",
  },
  UQA_CCCD: {
    label: "Số CCCD",
    type: "number",
    group: "UQ",
    subgroup: "BENA",
  },
  UQA_Date: {
    label: "Ngày sinh",
    type: "date",
    group: "UQ",
    subgroup: "BENA",
  },
  UQA_Noi_Cap: {
    label: "Nơi cấp",
    type: "select",
    options: ["Cục Cảnh sát QLHC về TTXH cấp", "Công an T. Đắk Lắk cấp"],
    group: "UQ",
    subgroup: "BENA",
  },
  UQA_Ngay_Cap: {
    label: "Ngày cấp",
    type: "date",
    group: "UQ",
    subgroup: "BENA",
  },
  UQA_Address: {
    label: "Địa chỉ",
    type: "address",
    group: "UQ",
    subgroup: "BENA",
  },
  // Bên B - Người được ủy quyền (nhập trực tiếp)
  UQ_Gender: {
    label: "Giới tính",
    type: "select",
    options: ["Ông", "Bà"],
    group: "UQ",
    subgroup: "INFO",
  },
  UQ_Name: {
    label: "Họ và tên",
    type: "text",
    group: "UQ",
    subgroup: "INFO",
  },
  UQ_CCCD: {
    label: "Số CCCD",
    type: "number",
    group: "UQ",
    subgroup: "INFO",
  },
  UQ_Date: {
    label: "Ngày sinh",
    type: "date",
    group: "UQ",
    subgroup: "INFO",
  },
  UQ_Noi_Cap: {
    label: "Nơi cấp",
    type: "select",
    options: ["Cục Cảnh sát QLHC về TTXH cấp", "Công an T. Đắk Lắk cấp"],
    group: "UQ",
    subgroup: "INFO",
  },
  UQ_Ngay_Cap: {
    label: "Ngày cấp",
    type: "date",
    group: "UQ",
    subgroup: "INFO",
  },
  UQ_Address: {
    label: "Địa chỉ",
    type: "address",
    group: "UQ",
    subgroup: "INFO",
  },
};

const groupLabels = {
  BCN: "Thông tin bên A",
  NCN: "Thông tin bên B",
  LAND: "Thông tin thửa đất",
  BD: "Thông tin đăng ký biến động đất đai",
  UQ: "Thông tin ủy quyền",
};

const subgroupLabels = {
  MEN1: "Thông tin cá nhân",
  MEN2: "Thông tin cá nhân",
  MEN3: "Thông tin cá nhân",
  MEN4: "Thông tin cá nhân",
  MEN5: "Thông tin cá nhân",
  MEN6: "Thông tin cá nhân",
  MEN7: "Thông tin cá nhân",
  INFO: "Thông tin chi tiết",
};

window.MEN_EXTRA_GROUPS = MEN_EXTRA_GROUPS;
window.MEN_EXTRA_GROUP_PLACEHOLDERS = MEN_EXTRA_GROUP_PLACEHOLDERS;
window.landTypeMap = landTypeMap;
window.phMapping = phMapping;
window.groupLabels = groupLabels;
window.subgroupLabels = subgroupLabels;
